# ---- identity of this installation (generated by the Inwom dashboard: "Add AWS environment") ----

variable "inwom_tenant_id" {
  description = "Tenant id shown in the Inwom dashboard (ten_...)."
  type        = string
  validation {
    condition     = can(regex("^ten_[a-z0-9]{8,40}$", var.inwom_tenant_id))
    error_message = "inwom_tenant_id must look like ten_xxxxxxxxxxxx."
  }
}

variable "inwom_environment_id" {
  description = "Environment id shown in the Inwom dashboard (env_...)."
  type        = string
  validation {
    condition     = can(regex("^env_[a-z0-9]{8,40}$", var.inwom_environment_id))
    error_message = "inwom_environment_id must look like env_xxxxxxxxxxxx."
  }
}

variable "bootstrap_token" {
  description = "Single-use registration token (expires 1 hour after creation). Stored in Secrets Manager; useless after the first successful registration."
  type        = string
  sensitive   = true
}

variable "config_signing_public_keys" {
  description = "Inwom config-signing public keys (base64url SPKI DER), shown in the dashboard and published at https://docs.inwom.com/security/keys. Pinned here: they are never fetched at runtime."
  type        = list(string)
  validation {
    condition     = length(var.config_signing_public_keys) >= 1 && length(var.config_signing_public_keys) <= 4
    error_message = "Provide between 1 and 4 signing keys (2 during rotation)."
  }
}

# ---- image: immutable, by digest ----

variable "image_repository" {
  description = "Repository of the signed Edge image (or your own ECR mirror of it)."
  type        = string
  default     = "ghcr.io/andresceballosm/inwom-edge"
}

variable "image_digest" {
  description = "Image digest, e.g. sha256:<64 hex>. Mutable tags are not accepted. Verify the signature first: deploy/security/verify-image.sh."
  type        = string
  validation {
    condition     = can(regex("^sha256:[a-f0-9]{64}$", var.image_digest))
    error_message = "image_digest must be an immutable digest (sha256:<64 hex>), not a tag."
  }
}

variable "ecr_repository_arn" {
  description = "Set only if image_repository is your own ECR mirror; grants the execution role read-only pull access to it."
  type        = string
  default     = null
}

# ---- network: outbound only ----

variable "vpc_id" {
  type = string
}

variable "subnet_ids" {
  description = "PRIVATE subnets whose route table sends 0.0.0.0/0 to your NAT gateway / egress firewall. The task never gets a public IP."
  type        = list(string)
}

variable "ingest_endpoint" {
  description = "Inwom ingestion endpoint (HTTPS, TLS 1.3, mTLS-capable)."
  type        = string
  default     = "https://ingest.inwom.com"
}

variable "allowed_egress_hosts" {
  description = "The only hostnames the Edge will connect to. Mirror this in your egress firewall (docs/edge/NETWORK_AND_EGRESS.md)."
  type        = list(string)
  default     = ["ingest.inwom.com"]
}

variable "egress_cidr_blocks" {
  description = "Destinations for outbound 443 from the task security group. Narrow to your NAT/firewall or Inwom's published egress ranges."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "create_vpc_endpoints" {
  description = "Create interface/gateway endpoints so calls to AWS services (S3, KMS, Logs, GuardDuty, Secrets Manager, ECR) stay on the AWS network."
  type        = bool
  default     = false
}

variable "route_table_ids" {
  description = "Route tables for the S3 gateway endpoint (only used when create_vpc_endpoints = true)."
  type        = list(string)
  default     = []
}

variable "ca_bundle_pem" {
  description = "Optional PEM trust anchor for the ingestion endpoint (private CA / validation). When set it is the ONLY CA trusted for that endpoint."
  type        = string
  default     = ""
}

variable "privatelink_service_name" {
  description = "RESERVED for a future AWS PrivateLink connection to Inwom. Not used in V1; leave null."
  type        = string
  default     = null
}

# ---- data sources the Edge may read (empty/false = not granted, not read) ----

variable "cloudtrail_access_mode" {
  description = <<-EOT
    DIRECT_READ: read your existing CloudTrail bucket. Only works if that bucket is NOT encrypted with a customer-managed KMS key
    (the Edge is never granted kms:Decrypt on a key you own for other purposes).
    CUSTOMER_TELEMETRY_MIRROR: this module creates a dedicated trail + bucket + KMS key owned by you, delivering only the selected
    telemetry; the Edge reads only that destination. Use this when your log bucket is KMS-encrypted.
  EOT
  type        = string
  default     = "DIRECT_READ"
  validation {
    condition     = contains(["DIRECT_READ", "CUSTOMER_TELEMETRY_MIRROR"], var.cloudtrail_access_mode)
    error_message = "cloudtrail_access_mode must be DIRECT_READ or CUSTOMER_TELEMETRY_MIRROR."
  }
}

variable "mirror_read_write_type" {
  description = "Which management events the dedicated mirror trail records: All (default; needed to see reconnaissance), WriteOnly, or ReadOnly."
  type        = string
  default     = "All"
  validation {
    condition     = contains(["All", "WriteOnly", "ReadOnly"], var.mirror_read_write_type)
    error_message = "mirror_read_write_type must be All, WriteOnly or ReadOnly."
  }
}

variable "mirror_retention_days" {
  description = "Objects in the telemetry mirror expire after this many days (the Edge only needs recent data)."
  type        = number
  default     = 7
}

variable "cloudtrail_bucket" {
  type    = string
  default = ""
}

variable "cloudtrail_prefixes" {
  description = "S3 key prefixes; may contain {yyyy}/{mm}/{dd}, e.g. AWSLogs/123456789012/CloudTrail/us-east-1/{yyyy}/{mm}/{dd}/"
  type        = list(string)
  default     = []
}

variable "waf_bucket" {
  type    = string
  default = ""
}

variable "waf_prefixes" {
  type    = list(string)
  default = []
}

variable "alb_bucket" {
  type    = string
  default = ""
}

variable "alb_prefixes" {
  type    = list(string)
  default = []
}

variable "vpc_flow_bucket" {
  type    = string
  default = ""
}

variable "vpc_flow_prefixes" {
  type    = list(string)
  default = []
}

variable "guardduty_detector_id" {
  type    = string
  default = ""
}

variable "cloudwatch_log_group_names" {
  description = "Security-relevant log groups to count filter matches in (content is never read into an export)."
  type        = list(string)
  default     = []
}

variable "enable_iam_metadata" {
  type    = bool
  default = false
}

variable "enable_compute_metadata" {
  description = "EC2 / EKS / ECS exposure metadata."
  type        = bool
  default     = false
}

# ---- privacy ceiling (the signed config from Inwom can only narrow this) ----

variable "max_privacy_mode" {
  description = "STRICT (default): pseudonymous actors/resources + behavioural features + counters. STANDARD: adds sanitized action names, service, region, coarse network metadata, normalized error codes. FORENSIC: also requires forensic_allowed_fields."
  type        = string
  default     = "STRICT"
  validation {
    condition     = contains(["STRICT", "STANDARD", "FORENSIC"], var.max_privacy_mode)
    error_message = "max_privacy_mode must be STRICT, STANDARD or FORENSIC."
  }
}

variable "forensic_allowed_fields" {
  description = "Per-source, per-field forensic allowlist, e.g. { CLOUDTRAIL = [\"SOURCE_IP\"] }. Empty = forensic export impossible, whatever Inwom Cloud requests."
  type        = map(list(string))
  default     = {}
}

variable "protected_resources" {
  description = "Resources YOU classify as significant (real names/ARNs). Tokenized inside the Edge; Inwom only ever receives the pseudonymous token + the class. Without this the engine has no defender context and stays uncertain."
  type = list(object({
    identifier     = string
    classification = string           # STANDARD | PROTECTED | RESTRICTED
    boundary       = optional(string) # IDENTITY | PRIVILEGE | DATA | EXECUTION | SECRET
  }))
  default = []
  validation {
    condition     = alltrue([for r in var.protected_resources : contains(["STANDARD", "PROTECTED", "RESTRICTED"], r.classification)])
    error_message = "classification must be STANDARD, PROTECTED or RESTRICTED."
  }
}

variable "enable_durable_queue" {
  description = "Create an Edge-owned, encrypted SQS queue so buffered telemetry survives task replacement."
  type        = bool
  default     = true
}

variable "queue_retention_seconds" {
  description = "Bounded retention of buffered telemetry (60 - 1209600). After this, undelivered telemetry is dropped (explicit policy)."
  type        = number
  default     = 345600
}

variable "pseudonym_key_version" {
  description = "Increment to rotate pseudonym tokens (breaks correlation across the boundary; see docs/edge/KEY_MANAGEMENT.md)."
  type        = number
  default     = 1
}

# ---- runtime ----

variable "name_prefix" {
  type    = string
  default = "inwom-edge"
}

variable "task_cpu" {
  type    = number
  default = 256
}

variable "task_memory" {
  type    = number
  default = 512
}

variable "spool_size_gib" {
  description = "Fargate ephemeral storage (21-200). The encrypted spool is bounded to half of it."
  type        = number
  default     = 21
}

variable "log_retention_days" {
  type    = number
  default = 30
}

variable "kms_deletion_window_days" {
  type    = number
  default = 30
}

variable "permissions_boundary_arn" {
  description = "Optional permissions boundary attached to both roles."
  type        = string
  default     = null
}
